/* Global sfx paths */
const SFX = {
    ARROW_HIT: "./sound/sfx/arrow_hit.mp3",
    ARROW_STICK: "./sound/sfx/arrow_stick.wav",
    BOW_SHOT: "./sound/sfx/bow_shoot.mp3",
    CLICK: "./sound/sfx/click.wav",
    SELECT: "./sound/sfx/pokemon_select.mp3",
    DISTRACT: "./sound/sfx/distract.mp3",
    ITEM_PICKUP: "./sound/sfx/item_pickup.mp3",
    SLASH1: "./sound/sfx/slash1.wav",
    SLASH2: "./sound/sfx/slash2.wav",
    JUMP: "./sound/sfx/jump.wav",
    JUMP2: "./sound/sfx/jump2.wav",
    DOUBLEJUMP: "./sound/sfx/double_jump.wav",
    WALLJUMP: "./sound/sfx/walljump.wav",
    CRITICAL: "./sound/sfx/critical.wav",
    DODGE: "./sound/sfx/dodge.wav",
    DAMAGED: "./sound/sfx/hit.mp3",
    HEAL: "./sound/sfx/heal.mp3",
    DRINK: "./sound/sfx/potion_drink.mp3",
    HEARTBEAT: "./sound/sfx/heartbeat.mp3",
    PLAYER_DEATH: "./sound/sfx/player_death.mp3",
    PLAYER_GRUNT: "./sound/sfx/player_grunt.wav",
    PLAYER_GRUNT2: "./sound/sfx/player_grunt2.wav",
    PLAYER_GRUNT3: "./sound/sfx/player_grunt3.wav",
    SHIELD_BLOCK: "./sound/sfx/shield_block.mp3",
    DOOR_ENTER: "./sound/sfx/door_enter.wav",
    CHEST_OPEN: "./sound/sfx/minecraft_chest_open.wav",
    OBELISK_ON: "./sound/sfx/loz_secret.mp3",
    NEW_ITEM: "./sound/sfx/zelda-new-item.mp3",
    NEW_HEART: "./sound/sfx/zelda-new-heart.mp3",
    PURCHASE: "./sound/sfx/ka-ching.mp3",
    ANVIL: "./sound/sfx/anvil.mp3",
    ENCHANTMENT: "./sound/sfx/enchantment.mp3",
    BERSERK_ACTIVATE: "./sound/sfx/sharingan.mp3",
    RESPAWN: "./sound/sfx/re_zero_respawn.mp3",
    COMPLETE: "./sound/sfx/finished.mp3",
    CHECKPOINT: "./sound/sfx/checkpoint.wav",
    TRIGGER: "./sound/sfx/event_trigger.mp3",
    EVIL_LAUGH: "./sound/sfx/evil_laugh.mp3",
    SUPER_SAIYAN: "./sound/sfx/super_saiyan.mp3",
    COMPLETION: "./sound/sfx/zelda-botw-first-contact.mp3",
    SNAP: "./sound/sfx/snap.mp3",
    FIREBALL_RELEASE: "./sound/sfx/fireball_release.mp3",
    TELEPORT: "./sound/sfx/teleport.mp3",
    TELEPORT2: "./sound/sfx/teleport2.mp3",
    KIBLAST: "./sound/sfx/kiblast.mp3",
    SWOOP: "./sound/sfx/swoop.mp3",
    SLAM: "./sound/sfx/hard_slam.wav",
    SWING: "./sound/sfx/hard_swing.wav",
    FIREBREATH: "./sound/sfx/demon_breath.wav",
    ROAR: "./sound/sfx/demon_roar.mp3",
    SMALL_FIREBALL: "./sound/sfx/small_fireball.mp3",

};

/** Global music paths */
const MUSIC = {
    CHASING_DAYBREAK: "./sound/music/FE3H_Chasing_Daybreak.mp3",
    FODLAN_WINDS: "./sound/music/FE3H_Fodlan_Winds.mp3",
    BETWEEN_HEAVEN_AND_EARTH: "./sound/music/FE3H_Between_Heaven_And_Earth.mp3",
    LONG_WAY: "./sound/music/P4_Long_Way.mp3",
    TITLE: "./sound/music/Runescape_Main.mp3",
    SPLENDOUR: "./sound/music/OSRS_splendour.mp3",
    SIGNORA: "./sound/music/Genshin_Signora_Phase_2.mp3",
    COUNTERATTACK: "./sound/music/OnePiece_Begin_Counterattack.mp3",
    MEMORIES: "./sound/music/OnePiece_Memories_ED.mp3",
    FOG: "./sound/music/P4_Fog.mp3",
    VEILED_IN_BLACK: "./sound/music/FFXV_Veiled_In_Black_Arrangement.mp3",
}
